# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --no-transfer-progress verify -Pall,sloeber_release,NOSDK -Dtest=NightlyJenkins -DfailIfNoTests=false 
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Repository
        path: io.sloeber.updatesite/target/repository
    - name: Archive Windows 64 bit
      uses: actions/upload-artifact@v2
      with:
        name: windows
        path: io.sloeber.product/target/products/io.sloeber.product/win32/win32/x86_64/
    - name: Archive Linux 64 bit
      uses: actions/upload-artifact@v2
      with:
        name: linux
        path: io.sloeber.product/target/products/io.sloeber.product/linux/gtk/x86_64/
    - name: Archive Mac 64 bit
      uses: actions/upload-artifact@v2
      with:
        name: macosx
        path: io.sloeber.product/target/products/io.sloeber.product/macosx/cocoa/x86_64        
    - name: Archive Mac ARM 64 bit
      uses: actions/upload-artifact@v2
      with:
        name: macosx_arm
        path: io.sloeber.product/target/products/io.sloeber.product/macosx/cocoa/aarch64
