# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.9.6
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Build Sloeber with Maven
      run: mvn --no-transfer-progress verify -Pall,sloeber_release,NOSDK -Dtest=NightlyJenkins -DfailIfNoTests=false 
      
    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Repository
        path: io.sloeber.updatesite/target/repository
    - name: Archive Windows 64 bit
      uses: actions/upload-artifact@v4
      with:
        name: sloeber-ide-sloeber_release-win32.win32.x86_64.zip
        path: io.sloeber.product/target/products/sloeber-ide-sloeber_release-win32.win32.x86_64.zip
    - name: Archive Linux 64 bit
      uses: actions/upload-artifact@v4
      with:
        name: sloeber-ide-sloeber_release-linux.gtk.x86_64.tar.gz
        path: io.sloeber.product/target/products/sloeber-ide-sloeber_release-linux.gtk.x86_64.tar.gz
    - name: Archive Mac 64 bit
      uses: actions/upload-artifact@v4
      with:
        name: sloeber-ide-sloeber_release-macosx.cocoa.x86_64.zip
        path: io.sloeber.product/target/products/sloeber-ide-sloeber_release-macosx.cocoa.x86_64.zip
    - name: Archive Mac ARM 64 bit
      uses: actions/upload-artifact@v4
      with:
        name: sloeber-ide-sloeber_release-macosx.cocoa.aarch64.zip
        path: io.sloeber.product/target/products/sloeber-ide-sloeber_release-macosx.cocoa.aarch64.zip
    - name: Build Sloeber SDK with Maven
      run: mvn clean verify -PSDK,win64,latest -DskipTests=true 
      